/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PasswordResetsTokenPut$Params {
  'Content-Type'?: string;
  token: string;
      body?: {
}
}

export function passwordResetsTokenPut(http: HttpClient, rootUrl: string, params: PasswordResetsTokenPut$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, passwordResetsTokenPut.PATH, 'put');
  if (params) {
    rb.header('Content-Type', params['Content-Type'], {});
    rb.path('token', params.token, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

passwordResetsTokenPut.PATH = '/password-resets/{token}';
