/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface OrderitemsGet$Params {}

export function orderitemsGet(
  http: HttpClient,
  rootUrl: string,
  params?: OrderitemsGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, orderitemsGet.PATH, 'get');
  if (params) {
    for (const key in params) {
      if (params.hasOwnProperty(key)) {
        rb.query(key, params[key as keyof OrderitemsGet$Params]);
      }
    }
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

orderitemsGet.PATH = '/orderitems';
