/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoriesGet$Params, categoriesGet } from '../fn/categorie/categories-get';
import { CategoriesIdDelete$Params, categoriesIdDelete } from '../fn/categorie/categories-id-delete';
import { CategoriesIdGet$Params, categoriesIdGet } from '../fn/categorie/categories-id-get';
import { CategoriesIdPut$Params, categoriesIdPut } from '../fn/categorie/categories-id-put';
import { CategoriesPost$Params, categoriesPost } from '../fn/categorie/categories-post';

@Injectable({ providedIn: 'root' })
export class CategorieService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `categoriesIdGet()` */
  static readonly CategoriesIdGetPath = '/categories/{id}';

  /**
   * Retrieve categorie.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdGet$Response(params: CategoriesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return categoriesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieve categorie.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdGet(params: CategoriesIdGet$Params, context?: HttpContext): Observable<any> {
    return this.categoriesIdGet$Response(params, context).pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `categoriesIdPut()` */
  static readonly CategoriesIdPutPath = '/categories/{id}';

  /**
   * Update categorie.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesIdPut$Response(params: CategoriesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return categoriesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update categorie.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesIdPut(params: CategoriesIdPut$Params, context?: HttpContext): Observable<any> {
    return this.categoriesIdPut$Response(params, context).pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `categoriesIdDelete()` */
  static readonly CategoriesIdDeletePath = '/categories/{id}';

  /**
   * Delete categorie.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdDelete$Response(
    params: CategoriesIdDelete$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<any>> {
    return categoriesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete categorie.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdDelete(params: CategoriesIdDelete$Params, context?: HttpContext): Observable<any> {
    return this.categoriesIdDelete$Response(params, context).pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `categoriesGet()` */
  static readonly CategoriesGetPath = '/categories';

  /**
   * List categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesGet$Response(params?: CategoriesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return categoriesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesGet(params?: CategoriesGet$Params, context?: HttpContext): Observable<any> {
    return this.categoriesGet$Response(params, context).pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }

  /** Path part for operation `categoriesPost()` */
  static readonly CategoriesPostPath = '/categories';

  /**
   * Create categorie.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesPost$Response(params?: CategoriesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return categoriesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create categorie.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesPost(params?: CategoriesPost$Params, context?: HttpContext): Observable<any> {
    return this.categoriesPost$Response(params, context).pipe(map((r: StrictHttpResponse<any>): any => r.body));
  }
}
