/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface AuthPost$Params {
  'Content-Type'?: string;
  header: {
    Authorization: string;
  };
}

export function authPost(
  http: HttpClient,
  rootUrl: string,
  params?: AuthPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, authPost.PATH, 'post');
  if (params) {
    rb.header('Content-Type', params['Content-Type'], {});
    rb.header('Authorization', params.header.Authorization, {});
    rb.body({}, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

authPost.PATH = '/auth';
